version: '3.8'

services:
  user-management-db:
    image: postgres:15-alpine
    container_name: Nest-Type-orm
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres      
      POSTGRES_PASSWORD: 1234      
      POSTGRES_DB: manu            
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:8.0-alpine
    container_name: redis-cache
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  pgdata:
    name: manu-db-data
    driver: local
  redis-data:
    name: redis-cache-data
    driver: local

networks:
  app-network:
    driver: bridge