@url=http://localhost:3000

### get guest users
GET {{url}}/guest-users

### GET GUEST BY ID
GET {{url}}/guest-users/1
### CREATE GUEST USER
POST {{url}}/guest-users
Content-Type: application/json

{
    "guest_id": 1,
  "email": "guest@example.com",
  "first_name": "mark",
  "last_name": "too",
    "phone_number": 1234567890

}
### UPDATE GUEST USER
PUT {{url}}/guest-users/1   
Content-Type: application/json

{
  "email": "guest_updated@example.com",
  "first_name": "mark_updated",
  "last_name": "too_updated",
  "phone_number": 1234567890
}
### DELETE GUEST USER
DELETE {{url}}/guest-users/1