@url = http://localhost:3000/bookings

### Get all bookings
GET {{url}}

### Get booking by ID
GET {{url}}/3
### Create a new booking
POST {{url}}
Content-Type: application/json

{
  "booking_id": 5,
  "user_id": 1,
  "vehicle_id": 2,
  "booking_date": "2023-10-01",
  "status": true,
  "return_date": "2023-10-05"
}

### Update booking by ID
PUT {{url}}/1
Content-Type: application/json

{
  "booking_id": 3,
  "user_id": 1,
  "vehicle_id": 2,
  "booking_date": "2023-10-01",
  "status": true,
  "return_date": "2023-10-05"
}

### Delete booking by ID
DELETE {{url}}/1